export const ALL_ISSUE_REQUEST = "ALL_ISSUE_REQUEST"
export const ALL_ISSUE_SUCCESS = "ALL_ISSUE_SUCCESS"
export const ALL_ISSUE_FAIL = "ALL_ISSUE_FAIL"

export const ISSUE_DETAILS_REQUEST = "ISSUE_DETAILS_REQUEST"
export const ISSUE_DETAILS_SUCCESS = "ISSUE_DETAILS_SUCCESS"
export const ISSUE_DETAILS_FAIL = "ISSUE_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"